name: Actualisation des données R

on:
  schedule:
    # Tous les lundis à 3h00 du matin
    - cron: '0 3 * * 1'
  workflow_dispatch: 

jobs:
  mise-a-jour:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Autorise l'écriture sur le dépôt

    steps:
      - name: 1. Récupérer les fichiers du dépôt
        uses: actions/checkout@v4

      - name: 2. Installer R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4'
          use-public-rspm: true # Installation rapide des packages

      - name: 3. Installer les packages R nécessaires
        run: Rscript -e 'install.packages(c("readr", "dplyr", "googlesheets4","tidyverse"))'

      - name: 4. Exécuter le script de traitement
        run: Rscript traitement_df.R

      - name: 5. Sauvegarder le nouveau fichier data_gps.csv sur GitHub
        run: |
          git config --local user.name "GitHub Actions Bot"
          git config --local user.email "actions@github.com"
          git add data_gps.csv
          git commit -m "Actualisation automatique de data_gps.csv" || echo "Aucune modification trouvée"
          git pull --rebase origin main
          git push
