name: Actualisation et Déploiement Shiny

on:
  schedule:
    - cron: '0 3 * * 1'
  workflow_dispatch:

jobs:
  mise-a-jour:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 1. Récupérer les fichiers
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # IMPORTANT : permet de charger tout l'historique pour éviter les conflits

      - name: 2. Installer R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4'
          use-public-rspm: true

      - name: 3. Installer les packages
        run: Rscript -e 'install.packages(c("readr", "dplyr", "googlesheets4", "rsconnect","tidyverse"))'

      - name: 4. Exécuter le script de traitement
        run: Rscript traitement_df.R

      - name: 5. Sauvegarder le fichier sur GitHub
        run: |
          git config --local user.name "GitHub Actions Bot"
          git config --local user.email "actions@github.com"
          
          # On s'assure que le robot est bien sur la branche principale
          git fetch origin main
          git checkout main
          
          # On ajoute et on valide le nouveau fichier
          git add data_gps.csv
          git commit -m "Actualisation automatique de data_gps.csv" || echo "Aucune modification trouvée"
          
          # On fusionne proprement (rebase) pour éviter tout conflit
          git pull --rebase origin main
          
          # On envoie le fichier
          git push origin main

      - name: 6. Déployer sur Shinyapps.io
        env:
          NAME: ${{ secrets.SHINYAPPS_NAME }}
          TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: |
          Rscript -e "rsconnect::setAccountInfo(name='$NAME', token='$TOKEN', secret='$SECRET')"
          Rscript -e "rsconnect::deployApp(appName = 'ComparativeDashboardDFCO',forceUpdate = TRUE)"
